export const translations = {
  ar: {
    title: 'أداة دمج ملفات PDF الاحترافية',
    subtitle: 'ادمج ملفات PDF المتعددة في ملف واحد بسرعة وأمان، مباشرة من متصفحك دون رفع ملفاتك لأي خادم.',
    dragDropText: 'اسحب ملفات PDF وأسقطها هنا',
    orBrowse: 'أو تصفح الملفات من جهازك',
    privacyNote: 'خصوصيتك آمنة بنسبة 100٪: تتم معالجة جميع الملفات محلياً على جهازك ولا نرفعها أبداً.',
    fileLimitNote: 'ملاحظة: يمكنك ترتيب الملفات بعد إضافتها للحصول على التنسيق المطلوب.',
    totalFiles: 'إجمالي الملفات:',
    totalPages: 'إجمالي الصفحات:',
    totalSize: 'الحجم الكلي:',
    clearAll: 'مسح القائمة',
    mergeBtn: 'ابدأ دمج الملفات الآن',
    merging: 'جاري دمج الملفات...',
    mergedSuccess: 'تم الدمج بنجاح!',
    downloadBtn: 'تحميل ملف PDF المدمج',
    mergeAgain: 'دمج ملفات جديدة',
    outputFileName: 'اسم الملف المدمج النهائي',
    filePlaceholder: 'دمج_ملفات_PDF',
    pageCountSuffix: 'صفحة',
    pagesCountSuffix: 'صفحات',
    readingPages: 'جاري قراءة عدد الصفحات...',
    errorNoFiles: 'يرجى إضافة ملفين على الأقل للدمج.',
    errorMergeFailed: 'عذرًا، حدث خطأ أثناء الدمج. يرجى التحقق من سلامة الملفات والمحاولة مرة أخرى.',
    orderUp: 'نقل لأعلى',
    orderDown: 'نقل لأسفل',
    deleteFile: 'حذف من القائمة',
    previewTitle: 'استعراض المستند المدمج',
    loadingPreview: 'جاري تحميل المعاينة...',
    noPreviewSupport: 'متصفحك لا يدعم المعاينة المباشرة للإطارات المضمنة، يمكنك تحميل الملف مباشرة لرؤيته.',
    dragActiveText: 'أفلت ملفاتك الآن ليتم إضافتها...',
    loadingPdfPages: 'جاري معالجة صفحات المستند...',
    invalidFileType: 'عذرًا، نقبل فقط ملفات بصيغة PDF.',
    filesAddedSuccess: 'تم إضافة الملفات بنجاح إلى القائمة.'
  },
  en: {
    title: 'Professional PDF Merger',
    subtitle: 'Merge multiple PDF files into one quickly and securely, right in your browser. Your files never leave your device.',
    dragDropText: 'Drag & drop PDF files here',
    orBrowse: 'or browse files from your device',
    privacyNote: 'Your privacy is 100% secure: All processing is done locally. Files are never uploaded to any server.',
    fileLimitNote: 'Note: You can easily reorder files to define their sequence in the merged document.',
    totalFiles: 'Total Files:',
    totalPages: 'Total Pages:',
    totalSize: 'Total Size:',
    clearAll: 'Clear List',
    mergeBtn: 'Start Merging Now',
    merging: 'Merging your files...',
    mergedSuccess: 'Merged Successfully!',
    downloadBtn: 'Download Merged PDF',
    mergeAgain: 'Merge New Files',
    outputFileName: 'Merged PDF Filename',
    filePlaceholder: 'merged_documents',
    pageCountSuffix: 'page',
    pagesCountSuffix: 'pages',
    readingPages: 'Reading page count...',
    errorNoFiles: 'Please add at least 2 PDF files to merge.',
    errorMergeFailed: 'An error occurred during merging. Please verify your PDFs and try again.',
    orderUp: 'Move Up',
    orderDown: 'Move Down',
    deleteFile: 'Remove File',
    previewTitle: 'Merged Document Preview',
    loadingPreview: 'Loading preview...',
    noPreviewSupport: 'Your browser doesn\'t support inline PDF previews. Please download to view.',
    dragActiveText: 'Drop your files here to add them...',
    loadingPdfPages: 'Analyzing PDF structures...',
    invalidFileType: 'Error: Only PDF documents are supported.',
    filesAddedSuccess: 'Files added loaded successfully.'
  }
};
